### ISSUE TITLE
Support for horizontal scrolling (on zoomed in image)

### ISSUE THREAD

**Issue by szpak** [infinyte7/image-occlusion-in-browser#18]
**Is your feature request related to a problem? Please describe.**
When zoomed in, I can scroll vertically with a mouse wheel, but I can't do the same to scroll horizontally.

**Describe the solution you'd like**
Horizontal scroll events should be intercepted and used.

**Comment by krmanik** [comment]
The image occlusion feature is natively supported in anki, if your feature related to native IO then https://forums.ankiweb.net/ can be used for feature request and discussion. The image-occlusion-in-browser project is in archive state now. So, no new feature or improvement done here, but if feature related to native IO then after discussion and demands it will be available in native IO.

**Comment by szpak** [comment]
> The image occlusion feature is natively supported in anki

I didn't know, nice!

> The image-occlusion-in-browser project is in archive state now

In that case, I will close this one and potentially create the new one for the native IO, if reproduced there.
