### ISSUE TITLE
Suggestion! xD

### ISSUE THREAD

**Issue by DostoievskiF** [infinyte7/image-occlusion-in-browser#3]
I have been following your hard work in the development of this application. Friend, your evolution has been exponential! I sincerely hope you don't give up! Unfortunately, I don't program. :(

However, I leave you a suggestion:
there is a less complete application than yours, called Anki Doodle. It does not, for example, have its role as a group cloze (incredible, in my humble opinion). Despite this, it has a very interesting interface, very intuitive to use, with a very practical way to automatically register flashcards directly on AnkiDroid (including images). Would it be possible for you to take advantage of some codes that are already applied there?

https://github.com/mmjang/Ankillusion
![image](https://user-images.githubusercontent.com/72423426/95149029-45d5f400-075b-11eb-941f-776d82df0c57.png)

Furthermore, it would be even better if you were able to implement a way to create both group clozes and individuals simultaneously, without having to change the "card creation mode". :)

### **Brother, thank you so much for your incredible work! xD**

**Comment by infinyte7** [comment]
Thanks for using this app.

I have tried to change the directory to 
``` AnkiDroid/collection.media/``` folder but file doesn't download in that case. I have searched for the possible implementation on Internet but still not found any working solution.

In next update I will try to update it.

If you have suggestion related to User Interface then comment it. Also, I do not use this app because so don't know possible use case, user intercase design etc. I will try to improve those ideas in next version of the app.

**Comment by DostoievskiF** [comment]
You are a genius, my friend!

Applying clozes with your application on notes (summaries, mind maps) made in the classroom is a sensational way to use this amazing tool! Very practical to create flashcards like that.
I use the text fields on the card to create the "question" to be answered by the cloze.

**Comment by DostoievskiF** [comment]
Brother, I let my suggestion 3 days ago! 

Are you some kind of **programming wizard**?! xD

**Comment by infinyte7** [comment]
Nope, good at googling :)

**Comment by DostoievskiF** [comment]
Bro! I thought of a very cool possible workflow in the application.

Is there any way to change from group to normal (or vice versa) without losing the inserted rectangles? I believe that this would be the easiest way to produce both group and clozes, according to the flow below:

**1) I create my group clozes and generate their cards.**
![image](https://user-images.githubusercontent.com/72423426/95514002-9c2c7800-0991-11eb-89f1-973025aff38f.png)

**2) I try to switch to normal mode.**
![image](https://user-images.githubusercontent.com/72423426/95514274-09d8a400-0992-11eb-9897-da87858bdd51.png)

**3) Unfortunately, I lose the created rectangles and the image. It would be nice to keep them, so that we could just click on the icon to create the individual cards with the same rectangles.**
![image](https://user-images.githubusercontent.com/72423426/95514315-1bba4700-0992-11eb-87b6-f5a717b87225.png)

OR 

**1) I draw my rectangles normally.** 
![image](https://user-images.githubusercontent.com/72423426/95515555-34c3f780-0994-11eb-9a9f-97ba002112fa.png)

**2) I click on the icon to enable group clozes.**
![image](https://user-images.githubusercontent.com/72423426/95515695-6c32a400-0994-11eb-8fe2-a0955d9a697d.png)

**3) I mark the group clozes I want.**
![image](https://user-images.githubusercontent.com/72423426/95515770-866c8200-0994-11eb-867a-3260c68cfd97.png)

**4) I click on the icon again to "turn off grouping".**
![image](https://user-images.githubusercontent.com/72423426/95515884-b451c680-0994-11eb-8444-59fa49a1c09e.png)

**5) Here is the difference! Again, when I turned on the grouping, I would create a NEW grouping of rectangles (with another color, perhaps).**
![image](https://user-images.githubusercontent.com/72423426/95516166-35a95900-0995-11eb-80ba-8ccab8231b4a.png)

**6) I click on the icon again to "turn off grouping". Finally, I click on the icon to create the cards. The result would be: the yellow rectangles would represent individual cards; the reds would represent a single card with group cloze; the greens would represent a single card with group cloze.**
![image](https://user-images.githubusercontent.com/72423426/95516337-799c5e00-0995-11eb-9d54-5bdb148a801d.png)

Again, I thank you from the bottom of my heart for all the amazing volunteer work you have been doing! Forgive me for insisting.

I would like to donate some money. Unfortunately, if I gave you all my money, you would be able to buy a glass of water. LoL. I am Brazilian, our currency is very bad ... Lmao.

**Comment by infinyte7** [comment]
I will update those ideas in next version. Thanks for suggestion. :)

**Comment by infinyte7** [comment]
For creating group cloze with different color. View 
https://github.com/infinyte7/image-occlusion-in-browser#how-to-group-cloze-with-different-color

**Comment by DostoievskiF** [comment]
### **You are a programming machine! Lol. Thank you very much, bro!** 😀

**Comment by DostoievskiF** [comment]
> For creating group cloze with different color. View
> https://github.com/infinyte7/image-occlusion-in-browser#how-to-group-cloze-with-different-color
> 
> Now create normal cloze and group cloze on same page without loosing rectangles on screen.

I saw that you already updated, very good! Regarding colors, in fact, in this process that I described from 1 to 6, the central idea was to be able, on the same screen, to create both individual cards and those grouped together. In image 6, the idea would be to click on the "produce cards icon" and generate the individual cards (in yellow), a card with grouped cards (red) and a different card with grouped clozes (blue). All of these cards would be generated simultaneously. 🙂

**Comment by infinyte7** [comment]
That can also be done.
1. Draw rectangles
2. Select group cloze button (top right) add rectangles to list.
3. Change question mask color from settings
4. Select more rectangles to list
5. Finally click done button to add notes data to AnkiDroid

**Comment by infinyte7** [comment]
![group_cloze_demo](https://user-images.githubusercontent.com/12841290/95605099-0d038b00-0a8b-11eb-81ed-58a7e03c254e.gif)

**Comment by DostoievskiF** [comment]
That's not it, bro! xD

The main idea described in steps 1 through 6 was to combine Normal and Cloze in one mode, so that by clicking the "done" button, I would produce both cards with normal clozes and cards with grouped clozes.
In your GIF, the correct thing would be: the yellow rectangles as individual clozes; the red rectangles are on only one card, with clozes grouped; the green rectangles are clozes grouped on a card separate from the red rectangles. You got it?

I did a simulation here at Gluta's Occlusion to give you an idea:
![Image-Occlusion-Enhanced-Add-Mod](https://user-images.githubusercontent.com/72423426/95617038-2d0e5c80-0a41-11eb-8a8f-915ba45f0e7c.gif)

![FelipeDirceu - Anki 2020-10-09 14-59-21 (1)](https://user-images.githubusercontent.com/72423426/95618818-0d2c6800-0a44-11eb-8cd7-8bae2ee9f3a9.gif)

**Comment by infinyte7** [comment]
Okay, understood.
It is little bit difficult to implement but I will try.

**Comment by infinyte7** [comment]
<img src="https://github.com/infinyte7/image-occlusion-in-browser/blob/master/demo/combine_cloze_demo_browser.gif?raw=true" height="400"></img>

**Comment by DostoievskiF** [comment]
You did an amazing work!! xD 

Bro, there is happening some problems with me: if you see below, I put 11 rectangles (11 possible cards). But the app only generated 9. I've tried it several times, with other images. The number of cards generated is always less.

![Screenshot_20201010-175753_Anki Image Occlusion](https://user-images.githubusercontent.com/72423426/95664846-d3319380-0b21-11eb-96d4-f2b016ebf0a4.jpg)

**Comment by infinyte7** [comment]
Check again in updates, it will work now.

**Comment by DostoievskiF** [comment]
> Check again in updates, it will work now.

### **It's WONDERFUL!**

Are you a self-taught programmer? You are very fast, bro!

**Comment by DostoievskiF** [comment]
### **It's WONDERFUL!**

> Check again in updates, it will work now.

Are you a self-taught programmer? You are very fast, bro!

**Comment by infinyte7** [comment]
Yep, Thanks
