### ISSUE TITLE
Tool: draw mode

### ISSUE THREAD

**Issue by FelipeDrytven** [infinyte7/image-occlusion-in-browser#4]
### **Hey, I saw that you keep updating the app! That's really good!**
 
Dude, I have a change suggestion for you. It would be nice if we didn't have to click on the "draw icon" every time we wanted to create new rectangles. You could modify it as follows: by touching it once, we can create rectangles infinitely. When we touch again, "turn off" the drawing rectangles "mode". To move the page during "drawing mode", we would drag with two fingers on the screen.

Thanks a lot for everything! Your app has revolutionized the way I study! :)

**Comment by infinyte7** [comment]
I have implemented it but not fully supported, in future update more improvements will be done.

Change it from settings, Enable Advanced Draw. But when draw button again clicked to turn off, then one extra rectangle will be created.

**Comment by FelipeDrytven** [comment]
**Thanks a lot!** 

I look forward to further improvements. In case you are interested, I have a small suggestion for improvement related to the new tool. When I am creating rectangles in "draw mode", when clicking on another rectangle, it does not interrupt the mode. Because of that, he ends up creating a new rectangle under what I touched. _It would be nice if he interrupted, so that I could move the touched rectangle freely, without fear of creating a new one under it._

It's just a small suggestion. I work around this problem by deactivating "draw mode" before touching a rectangle I had already placed.

**Comment by infinyte7** [comment]
Yes, I have tried to implement those but I haven't found any working solution for those. So, in next release, may be I solve those bugs.

**Comment by FelipeDrytven** [comment]
# **Your app is INCREDIBLE! :)**

Is there something that I can do to help you or contribute with you in your project?

**Comment by infinyte7** [comment]
If found any bug or issues, leave a comment. Thanks

**Comment by FelipeDrytven** [comment]
Thank you!

I found a bug. When I have "draw mode" enabled and click on the icon to group clozes, it does not turn off "draw mode".
I have a new suggestion for you! Is it possible to "send" an image file directly to the occlusion Android app, without having to open it first? Like this:

![image](https://user-images.githubusercontent.com/70224437/95893183-fb0d3b00-0d5d-11eb-9b43-82d5da3944c3.png)

**Comment by infinyte7** [comment]
I will look in those bug.

Adding image to app from gallery may be not possible because the app is like website. It will first load then open selected image. It is doable but difficult.

**Comment by FelipeDrytven** [comment]
Thanks a lot for your help!

> 
> 
> I will look in those bug.
> 
> Adding image to app from gallery may be not possible because the app is like website. It will first load then open selected image. It is doable but difficult.

Thank you very much for your help! :)

**Comment by DostoievskiF** [comment]
Wow! Excellent suggestion. In fact, it would be really cool not to have to turn off "draw mode" before touching the cloze group icon! xD

It would be better if it was turned off when I tap the group icon. The same goes for the delete button. When I touch the rectangle and then the delete, it doesn't work, with the need to turn off "draw mode" first.

Another cool suggestion would be to improve the delete button. Sometimes it gets buggy. I select the rectangle and it does not delete.
So, I suggest something like "draw mode": "delete mode". When I touched the delete icon, it would turn the mode on, allowing me to delete any rectangles I want to touch. Once deleted, I tap the icon again, turning off "delete mode".

**Comment by infinyte7** [comment]
In free time, I will look in to these features.

**Comment by FelipeDrytven** [comment]
Thanks a lot, Mani! 

Again, I have another suggestion! xD 

Is it possible to add some kind of "text box" over the Image? So, the text box would disappear when we click to show answer.

**Comment by infinyte7** [comment]
It can be done. I will implement those features in next month.
(Classes and assignments)
:)

**Comment by infinyte7** [comment]
It can be done. To be added in next release.
:)

**Comment by FelipeDrytven** [comment]
Hey, Mani! I am very happy that you have returned to the development of the app! :)
Bro, I downloaded the latest version and found some bugs: I can't delete / undo grouped clozes.
I really liked the new features you added!

**Comment by infinyte7** [comment]
Try again with updated version. :)

**Comment by FelipeDrytven** [comment]
Hi, bro!! :)

I was thinking about a suggestion to your app. 
I believe that adding an option to crop the image - without losing resolution quality - would be very useful.

Thank you for absolutely EVERYTHING! =D

**Comment by infinyte7** [comment]
It will be implemented in next update.

**Comment by FelipeDrytven** [comment]
This is awesome! ;)

**Comment by FelipeDrytven** [comment]
Hey, bro! 
Excuse me, but do you have any update forecast?

**Comment by infinyte7** [comment]
May be End of December.

**Comment by FelipeDrytven** [comment]
**Hey, Mani! ;D**

How are you, bro? Are you still on the Anki Occlusion project?

**Comment by infinyte7** [comment]
Hi, Thanks 
I have created pull request on https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7998
So, It can be downloaded from F-Droid. Waiting for merge of this PR to F-Droid.

**Comment by FelipeDrytven** [comment]
**Wow, I'm so glad with your return, bro!**

**Comment by FelipeDrytven** [comment]
Do you have plans to the app? xD

**Comment by infinyte7** [comment]
Crop image will be next update.
