### ISSUE TITLE
No mention of version in Android app. 

### ISSUE THREAD

**Issue by dummifiedme** [infinyte7/image-occlusion-in-browser#5]
Hi,
Thanks for the tool, I am just raising an issue as I felt it's important to have a mention of code/app Version in the app. 

I couldn't find it and hence couldn't know if I need an update or not. 

If I am missing something here, feel free to mark this solved.

**Comment by infinyte7** [comment]
![d](https://user-images.githubusercontent.com/12841290/98434184-71584f80-2108-11eb-83a4-8c91bc0ba19e.PNG)

I will implement feature ```update app``` in next release.

**Comment by infinyte7** [comment]
![d](https://user-images.githubusercontent.com/12841290/98434237-ea57a700-2108-11eb-96a3-22a16edd1439.PNG)

I will implement ```update app``` feature in next release.

**Comment by dummifiedme** [comment]
> ![d](https://user-images.githubusercontent.com/12841290/98434237-ea57a700-2108-11eb-96a3-22a16edd1439.PNG)
> 
> I will implement `update app` feature in next release.

Thanks. 
Pardon me for the troubles.
