### ISSUE TITLE
Thanks a lot

### ISSUE THREAD

**Issue by kmz123** [infinyte7/image-occlusion-in-browser#6]
I have my exams coming up and I hadn't made my image flashcards yet. I was literally planning manually edit picture after picture to make it.

Since I couldn't find any other way to message you, here's my thanks.

**Comment by infinyte7** [comment]
Thanks for using the app.

**Comment by kmz123** [comment]
Hey Mani,

The only other major feature missing in the ankidroid is being able to import using .csv I did watch your video and that's a bit too complicated for me who doesn't code.

I asked the mods at ankidroid and one of them told me that the backend of that feature is done and it only needs a GUI. (https://github.com/ankidroid/Anki-Android/issues/6772). 

Since you have already done an awesome job with the image occlusion app, will you be interested in doing the GUI?

**Comment by infinyte7** [comment]
I may look into this feature after my semester exam. 
If you explain the complexity in procedure to create deck or image occlusion then may be I try to reduce the complexity.

1. For converting csv to deck use this website
https://infinyte7.github.io/Anki-Export-Deck-tkinter/

2. For image occlusion for android
https://github.com/infinyte7/image-occlusion-in-browser/releases/tag/v1.3.5

**Comment by kmz123** [comment]
As I told previously I am not a coder, so these are the parts that are too hard for me to do

Install Pydroid 3 from Play Store.
Install genanki python library inside Pydroid using pip.
Then download Anki Deck Export Tkinter
Run this script
Select file and fields separated by (tab, comma)
6. Click Import
7. Enter file name, title name, model name.
8. Enter name of fields to be mapped

I think the biggest problem is the fact that I have to run some 'script'. Is there any way I can use the CSV tool on android without doing that.


Note - The image occlusion app is very easy to use and I'm not having any problems with learning how to use it

**Comment by infinyte7** [comment]
I have made the web version for exporting deck

https://infinyte7.github.io/Anki-Export-Deck-tkinter/

No need to install anything. Create deck in three steps.
1. Import csv or tsv file
2. Enter fields name and export
3. Download generated deck

If still found any complexity in using this web version then let me know. I will try to reduce the complexity by adding features to web version.

**Comment by kmz123** [comment]
It's not loading on my phone

**Comment by infinyte7** [comment]
Okay, I have already made an app to convert csv and tsv file to apkg. But it not finished yet. I think the app version may work. Stay tuned for the updates.

**Comment by kmz123** [comment]
Awesome, thanks a lot

**Comment by kmz123** [comment]
Just so I can mark my calendar, do you have any idea of the date that you are going to release it

**Comment by kmz123** [comment]
Also... Do you have any plans of making a heat map addon for ankidroid

**Comment by infinyte7** [comment]
Try this, it is still need improvements.
https://github.com/infinyte7/Anki-Export-Deck-tkinter/releases

Download apk from assets section

**Comment by kmz123** [comment]
Sure, I'll try it out
<div id="DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br />
<table style="border-top: 1px solid #D3D4DE;">
	<tr>
        <td style="width: 55px; padding-top: 13px;"><a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank"><img
src="https://ipmcdn.avast.com/images/icons/icon-envelope-tick-round-orange-animated-no-repeat-v1.gif"
alt="" width="46" height="29" style="width: 46px; height: 29px;"
/></a></td>
		<td style="width: 470px; padding-top: 12px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Virus-free. <a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank" style="color: #4453ea;">www.avast.com</a>
		</td>
	</tr>
</table><a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1"
height="1"></a></div>

**Comment by kmz123** [comment]
The app isn't loading

**Comment by infinyte7** [comment]
I have modified my existing project to be run inside termux. 

### View this
https://github.com/infinyte7/Anki-Export-Deck-tkinter/releases/tag/0.1-localhost

### Demo
View [Demo](https://user-images.githubusercontent.com/12841290/99376711-3f14d200-2900-11eb-8828-f29a6b01840d.gif)

**Comment by simonsaysburrow** [comment]
Thanks so much @krmanik for the work that you've put into this app!

Your Patreon page below says it have been removed.
https://www.patreon.com/kr_mani

Is there another way that we can support this app?

Thanks,

Simon

![image](https://user-images.githubusercontent.com/93038310/163328358-2193835a-ab1c-4c90-8ad8-73ee13e1b413.png)


![image](https://user-images.githubusercontent.com/93038310/163328189-7e8452db-4471-4a31-b6b6-f6d6761af9a3.png)

**Comment by krmanik** [comment]
Currently the project is not actively maintained so removed the link. It will added later when project will released with new features and fixes. Thanks

**Comment by simonsaysburrow** [comment]
Thanks for that @krmanik.
I've like using your app so much that I created a small course on it - anyone can access it free [here](https://www.skillshare.com/classes/How-to-create-an-Anki-image-occlusion-card-on-an-Android-phone/369418665/projects?discount=XNKS9&teacherRef=545824935&via=free-enrollment&utm_campaign=teacher-discount-369418665&utm_source=ShortUrl&utm_medium=teacher-discount).
(The first video can be watched without a Skillshare account and the remaining videos can be watched after signing up for a free Skillshare account.)
Definitely keen for any feedback on it :)

![image](https://user-images.githubusercontent.com/93038310/175768908-4ca982fc-d4b2-46ac-ae10-ebbfc83c64bb.png)

**Comment by krmanik** [comment]
Hi, It is really nice. It will be helpful for the app user. I think you should post it to Anki discord channel and subreddit. More people will appreciate it.
Thanks
